name: Run go4gold

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build Go binary
        run: |
          go build -o go4gold 

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: go4gold
          path: ./go4gold
