name: Run go4gold

on:
  push:
    branches:
      - main

jobs:
  run-tool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build Go application
        run: |
          go build -o go4gold

      - name: Run infrastructure tool
        run: |
          ./go4gold 
          #-config ./on-cloud/variables.yaml -infra ./on-cloud/infra.yaml