name: Run go4gold

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'  # Replace with your Go version

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Build Go binary
        run: |
          go build -o go4gold 

      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: go4gold
          path: ./version/go4gold
